BEGIN
    EXECUTE IMMEDIATE 'DROP USER App_admin CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1918 THEN
            RAISE;
        END IF;    
END;
/

CREATE USER App_admin IDENTIFIED BY "PasswordMaverick1";
GRANT CONNECT, RESOURCE TO App_admin;
GRANT CREATE SESSION TO App_admin WITH ADMIN OPTION;
GRANT CREATE TABLE TO App_admin;
ALTER USER App_admin QUOTA UNLIMITED ON DATA;
GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE TRIGGER TO App_admin;
GRANT CREATE USER TO App_admin;
GRANT DROP USER TO App_admin;
