--Drop Tables
 
 
SET SERVEROUTPUT ON
 
BEGIN
    FOR I IN (
        WITH MYTABLES AS (
            SELECT 'USER_PRODUCT' AS TNAME FROM DUAL
            UNION ALL SELECT 'PAYMENT' FROM DUAL
            UNION ALL SELECT 'ORDER_TABLE' FROM DUAL
            UNION ALL SELECT 'USER_TABLE' FROM DUAL
            UNION ALL SELECT 'WARE_PRODUCT' FROM DUAL
            UNION ALL SELECT 'PRODUCT' FROM DUAL
            UNION ALL SELECT 'PRODUCT_CATEGORY' FROM DUAL
            UNION ALL SELECT 'ROLES' FROM DUAL
            UNION ALL SELECT 'WAREHOUSE' FROM DUAL
        )
        SELECT M.TNAME
        FROM MYTABLES M INNER JOIN USER_TABLES O ON M.TNAME = O.TABLE_NAME
    )
    LOOP
        BEGIN
            DBMS_OUTPUT.PUT_LINE('TABLE NAME TO BE DROPPED: ' || I.TNAME);
            EXECUTE IMMEDIATE 'DROP TABLE ' || I.TNAME;
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE(SQLERRM);
        END;
    END LOOP;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/
-------------------------------------------
 
--Drop sequences
 
 
--select * from user_sequences;
 
 
SET SERVEROUTPUT ON
 
BEGIN
    FOR I IN (
        WITH MYSEQUENCES AS (
            SELECT 'PAYMENT_ID_SEQ' AS SEQ_NAME FROM DUAL
            UNION ALL SELECT 'PRODUCT_ID_SEQ' FROM DUAL
            UNION ALL SELECT 'USER_ID_SEQ' FROM DUAL
            UNION ALL SELECT 'ROLE_ID_SEQ' FROM DUAL
            UNION ALL SELECT 'ORDER_ID_SEQ' FROM DUAL
            UNION ALL SELECT 'WAREHOUSE_ID_SEQ' FROM DUAL
            UNION ALL SELECT 'CATEGORY_ID_SEQ' FROM DUAL
            UNION ALL SELECT 'USER_PRODUCT_ID_SEQ' FROM DUAL
            UNION ALL SELECT 'WARE_PRODUCT_ID_SEQ' FROM DUAL
        )
        SELECT M.SEQ_NAME
        FROM MYSEQUENCES M INNER JOIN USER_SEQUENCES O ON M.SEQ_NAME = O.SEQUENCE_NAME
    )
    LOOP
        BEGIN
            DBMS_OUTPUT.PUT_LINE('SEQUENCE TO BE DROPPED: ' || I.SEQ_NAME);
            EXECUTE IMMEDIATE 'DROP SEQUENCE ' || I.SEQ_NAME;
        EXCEPTION
            WHEN OTHERS THEN
                DBMS_OUTPUT.PUT_LINE(SQLERRM);
        END;
    END LOOP;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/
 
------------------------------------------------------
 
-- Create Sequences
CREATE SEQUENCE ROLE_ID_SEQ START WITH 1;
CREATE SEQUENCE CATEGORY_ID_SEQ START WITH 1;
CREATE SEQUENCE WAREHOUSE_ID_SEQ START WITH 1;
CREATE SEQUENCE PRODUCT_ID_SEQ START WITH 1;
CREATE SEQUENCE WARE_PRODUCT_ID_SEQ START WITH 1;
CREATE SEQUENCE USER_ID_SEQ START WITH 1;
CREATE SEQUENCE ORDER_ID_SEQ START WITH 1;
CREATE SEQUENCE USER_PRODUCT_ID_SEQ START WITH 1;
CREATE SEQUENCE PAYMENT_ID_SEQ START WITH 1;


